on:
  pull_request: 
    branches: [main, dev]

name: document_and_style

jobs:
  document:
    name: Document and Style
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GCPTOOLS_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch head of current pull request
        uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GCPTOOLS_PAT}}

      - name: Setup instance of R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages and dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::roxygen2
            any::styler
          needs: pr-document

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Commit changes
        run: |
          {
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          if [ -z "$(git status --porcelain)" ]
          then
            echo "No changes to Documentation"
          else
            git add man/\* NAMESPACE DESCRIPTION
            git commit -m 'Document'
          fi
          } || {
          echo "Something went wrong"
          exit 1
          }
          
      - name: Style
        run: styler::style_pkg()
        shell: Rscript {0}

      - name: Commit changes
        run: |
          {
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          if [ -z "$(git status --porcelain)" ]
          then
            echo "No changes to styling"
          else
            git commit -am 'Style'
          fi
          } || {
          echo "Something went wrong"
          exit 1
          }   
      - name: Push Changes
        uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GCPTOOLS_PAT}}
