# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main ]   

name: Test Coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GCPTOOLS_PAT }}
    strategy:
      matrix:
        r-version: ['4.2.2']
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup instance of R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: ${{ matrix.r-version }}

      - name: Install packages and dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: covr::codecov( token = "${{ secrets.CODECOV_TOKEN }}", quiet = FALSE )
        shell: Rscript {0}
        
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
        

